org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric properties (Minecraft 1.21.11)
minecraft_version=1.21.11
loader_version=0.18.1
loom_version=1.14-SNAPSHOT

# Mod properties
mod_version=1.0.0
maven_group=com.nangclient
archives_base_name=nangclient

# Dependencies
fabric_api_version=0.141.6+1.21.11
